baseURL = "https://streetart.netlify.com"
languageCode = "en-us"
title = "Gaz Slum Art from the Streets"
theme = "hugo-shopping-product-catalogue-simple"
[Params]
description = "Check out my latest hand made creations of necklaces, bracelets, earings, pendants, textiles & art."
