baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "Gaz Slum Art from the Streets"
theme = "hugo-shopping-product-catalogue-simple"
[Params]
description = "This is real hip hop, this is true ghetto love."
